parameters:
  annotated_bundle_resolvers.cache_path: '%kernel.cache_dir%/annotations'
  annotations.cache_ttl_default: 3600
services:
  # конфигурация по умолчанию в *этом* файле
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  # Читатель аннотаций
  annotated_bundle_resolvers.annotation_reader:
    class: Spiral\Attributes\AnnotationReader

  # Читатель атрибутов PHP 8
  annotated_bundle_resolvers.attribute_reader:
    class: Spiral\Attributes\AttributeReader

  # Совмещенный читатель аннотаций Доктрины и аттрибутов PHP 8
  annotated_bundle_resolvers.annotations_selective_reader:
    class: Spiral\Attributes\Composite\SelectiveReader
    arguments:
      - ['@annotated_bundle_resolvers.attribute_reader', '@annotated_bundle_resolvers.annotation_reader' ]

  # Кэшированный вариант совмещенного читателя
  annotated_bundle_resolvers.psr6_selective_reader:
    class: Spiral\Attributes\Psr6CachedReader
    arguments:
      - '@annotated_bundle_resolvers.annotations_selective_reader'
      - '@annotated_bundle_resolvers.filesystem_cache_adapter'

  # PSR-6 cache adapter
  annotated_bundle_resolvers.filesystem_cache_adapter:
    class: Symfony\Component\Cache\Adapter\FilesystemAdapter
    arguments:
      - 'annotations'
      - '%annotations.cache_ttl_default%'
      - '%annotated_bundle_resolvers.cache_path%'
