services:
  # конфигурация по умолчанию в *этом* файле
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  # Валидатор Symfony
  annotated_bundle_resolvers.validator:
    public: false
    class: Symfony\Component\Validator\Validator\ValidatorInterface
    factory: ['Symfony\Component\Validator\Validation', 'createValidator']

  annotated_bundle_resolvers.controller_resolver:
    public: false
    class: Symfony\Bundle\FrameworkBundle\Controller\ControllerResolver

  Spiral\Attributes\AttributeReader: ~

  # Валидатор запроса.
  annotated_bundle_resolvers.validator_request:
    public: false
    class: Prokl\AnnotatedParamResolverBundle\ArgumentResolver\Validator\RequestAnnotationValidator
    arguments:
      - '@annotated_bundle_resolvers.annotations.cached_reader'
      - '@annotated_bundle_resolvers.validator'
      - '@serializer'
      - '@Spiral\Attributes\AttributeReader'

  Prokl\AnnotatedParamResolverBundle\ArgumentResolver\Validator\RequestAnnotationValidatorInterface: '@annotated_bundle_resolvers.validator_request'

  # Request в DTO.
  # Важно: priority должно быть установлено как можно больше,
  # иначе все зашибает симфонический ServiceValueResolver и до этого ресолвера
  # дело не доходит.
  annotated_bundle_resolvers.unserialize_request:
    class: Prokl\AnnotatedParamResolverBundle\ArgumentResolver\RequestBodyArgumentResolver
    arguments:
      - '@annotated_bundle_resolvers.annotations.cached_reader'
      - '@annotated_bundle_resolvers.controller_resolver'
      - '@serializer'
      - '@annotated_bundle_resolvers.validator_request'
      - '@Spiral\Attributes\AttributeReader'
    tags:
      - { name: controller.argument_value_resolver, priority: 1500 }

  # $_GET параметры в DTO.
  annotated_bundle_resolvers.query_params:
    class: Prokl\AnnotatedParamResolverBundle\ArgumentResolver\QueryParamsArgumentResolver
    arguments:
      - '@annotated_bundle_resolvers.annotations.cached_reader'
      - '@annotated_bundle_resolvers.controller_resolver'
      - '@serializer'
      - '@annotated_bundle_resolvers.validator_request'
      - '@property_info'
      - '@Spiral\Attributes\AttributeReader'
    tags:
      - { name: controller.argument_value_resolver, priority: 1500 }

  # $_POST параметры в DTO.
  annotated_bundle_resolvers.post_params:
    class: Prokl\AnnotatedParamResolverBundle\ArgumentResolver\RequestParamArgumentResolver
    arguments:
      - '@annotated_bundle_resolvers.annotations.cached_reader'
      - '@annotated_bundle_resolvers.controller_resolver'
      - '@serializer'
      - '@annotated_bundle_resolvers.validator_request'
      - '@property_info'
      - '@Spiral\Attributes\AttributeReader'
    tags:
      - { name: controller.argument_value_resolver, priority: 1500 }
